input:
  actions:
    camera.pan:
      axis2:
        mouse_drag:
          button: Right
          scale: [1.0, 1.0]
        edge_scroll: true
    camera.rotate:
      axis2:
        mouse_drag:
          button: Middle
          scale: [1.0, -1.0]
    camera.zoom:
      scalar:
        mouse_wheel_y: -1.0
    player.move:
      axis2:
        keys:
          positive_y: [W]
          negative_y: [S]
          positive_x: [D]
          negative_x: [A]
